name: Server Unit Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install deps
        working-directory: ./server
        run: yarn install

      - name: Run unit tests
        working-directory: ./server
        run: npm run test

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Run integration tests
        run: npm run test:integration
